apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gau-account-service-hpa
  namespace: gau-${DEPLOY_ENV}-env
  labels:
    app: gau-account-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gau-account-api-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70